### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by Dacesilian** [geeks-r-us/mqtt-panel#12]
There are compile errors and I'm unable to get it running. Can you please check it out?
I'm on Windows and using master from git.

```
# yarn install
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.12: The platform "win32" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @babel/preset-env@7.9.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/helper-compilation-targets@7.8.7" has unmet peer dependency "@babel/core@^7.0.0".
warning "@babel/preset-env > @babel/plugin-proposal-async-generator-functions@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-dynamic-import@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-json-strings@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-nullish-coalescing-operator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-numeric-separator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-object-rest-spread@7.9.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-optional-catch-binding@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-optional-chaining@7.9.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-unicode-property-regex@7.8.8" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-async-generators@7.8.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-dynamic-import@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-json-strings@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-nullish-coalescing-operator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-numeric-separator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-object-rest-spread@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-optional-catch-binding@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-optional-chaining@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-top-level-await@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-arrow-functions@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-async-to-generator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-block-scoped-functions@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-block-scoping@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-classes@7.9.2" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-computed-properties@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-destructuring@7.8.8" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-dotall-regex@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-duplicate-keys@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-exponentiation-operator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-for-of@7.9.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-function-name@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-literals@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-member-expression-literals@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-modules-amd@7.9.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-modules-commonjs@7.9.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-modules-systemjs@7.9.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-modules-umd@7.9.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-named-capturing-groups-regex@7.8.3" has unmet peer dependency "@babel/core@^7.0.0".
warning "@babel/preset-env > @babel/plugin-transform-new-target@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-object-super@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-parameters@7.9.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-property-literals@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-regenerator@7.8.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-reserved-words@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-shorthand-properties@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-spread@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-sticky-regex@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-template-literals@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-typeof-symbol@7.8.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-unicode-regex@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/preset-modules@0.1.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-unicode-property-regex > @babel/helper-create-regexp-features-plugin@7.8.8" has unmet peer dependency "@babel/core@^7.0.0".
warning "@grafana/runtime > @grafana/ui > storybook-dark-mode@0.4.0" has unmet peer dependency "@storybook/api@>= 5.x".
warning "@grafana/runtime > @grafana/ui > storybook-dark-mode@0.4.0" has unmet peer dependency "@storybook/addons@>= 5.x".
warning "@grafana/runtime > @grafana/ui > storybook-dark-mode@0.4.0" has unmet peer dependency "@storybook/components@>= 5.x".
warning "@grafana/runtime > @grafana/ui > storybook-dark-mode@0.4.0" has unmet peer dependency "@storybook/core-events@>= 5.x".
warning "@grafana/runtime > @grafana/ui > storybook-dark-mode@0.4.0" has unmet peer dependency "@storybook/theming@>= 5.x".
warning "@grafana/runtime > @grafana/ui > @grafana/slate-react > slate-react-placeholder@0.2.9" has unmet peer dependency "slate-react@>=0.22.0".
warning "@grafana/toolkit > @grafana/eslint-config@1.0.0-rc1" has incorrect peer dependency "eslint-plugin-jsdoc@^21.0.0".
[5/5] Building fresh packages...
Done in 26.33s.

```

And build:
```
# yarn build
yarn run v1.22.5
$ grafana-toolkit plugin:build
√ Preparing
√ Linting
 PASS  src/module.test.ts

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.174s
Ran all test suites with tests matching "".
√ Running tests
- Compiling...  Trace: SyntaxError: C:\Java\mqtt-panel3\src\plugin.json: Unexpected token n in JSON at position 468
      at parse (<anonymous>)
      at Object.Module._extensions..json (internal/modules/cjs/loader.js:1171:22)
      at Module.load (internal/modules/cjs/loader.js:985:32)
      at Function.Module._load (internal/modules/cjs/loader.js:878:14)
      at Module.require (internal/modules/cjs/loader.js:1025:19)
      at require (internal/modules/cjs/helpers.js:72:18)
      at Object.exports.getPluginId (C:\Java\mqtt-panel3\node_modules\@grafana\src\config\utils\getPluginId.ts:7:24)
      at Object.exports.getFileLoaders (C:\Java\mqtt-panel3\node_modules\@grafana\src\config\webpack\loaders.ts:163:40)
      at C:\Java\mqtt-panel3\node_modules\@grafana\src\config\webpack.plugin.config.ts:244:12
      at step (C:\Java\mqtt-panel3\node_modules\@grafana\toolkit\node_modules\tslib\tslib.js:136:27)
      at Object.next (C:\Java\mqtt-panel3\node_modules\@grafana\toolkit\node_modules\tslib\tslib.js:117:57)
      at fulfilled (C:\Java\mqtt-panel3\node_modules\@grafana\toolkit\node_modules\tslib\tslib.js:107:62)
      at C:\Java\mqtt-panel3\node_modules\@grafana\src\cli\utils\useSpinner.ts:13:15
      at step (C:\Java\mqtt-panel3\node_modules\@grafana\toolkit\node_modules\tslib\tslib.js:136:27)
      at Object.throw (C:\Java\mqtt-panel3\node_modules\@grafana\toolkit\node_modules\tslib\tslib.js:117:57)
      at rejected (C:\Java\mqtt-panel3\node_modules\@grafana\toolkit\node_modules\tslib\tslib.js:108:69)
× C:\Java\mqtt-panel3\src\plugin.json: Unexpected token n in JSON at position 468
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Thank you!

**Comment by Dacesilian** [comment]
Same error with different line is under Debian:

`mqtt-panel/src/plugin.json: Unexpected token n in JSON at position 449`

# nodejs --version
v12.18.4

# yarn --version
1.22.5

**Comment by geeks-r-us** [comment]
I found the issue. Will be fixed with next release.

**Comment by ManuelBu96** [comment]
When will the new Version be available?

**Comment by ManuelBu96** [comment]
> 
> 
> Same error with different line is under Debian:
> 
> `mqtt-panel/src/plugin.json: Unexpected token n in JSON at position 449`
> # nodejs --version
> 
> v12.18.4
> # yarn --version
> 
> 1.22.5

You have to update the plugin.json from
`"screenshots": [
      {name: "Controls", path: "img/controls.png",},
      {name: "Server settings", path: "img/server.png"}
    ],`
to
`"screenshots": [
      {
		"name": "Controls",
		"path": "img/controls.png"
	  },
      {
		"name": "Server settings",
		"path": "img/server.png"
	  }
    ],`

**Comment by geeks-r-us** [comment]
Version is in progress. 
Current critical path is the signing process and I wait on a answer from the Grafana team to adapt the deployment for Grafana 7
