### ISSUE TITLE
Cannot get this plugin to work

### ISSUE THREAD

**Issue by Jhdgkss** [geeks-r-us/mqtt-panel#28]
Hi i am having trouble installing this plugin.
I used Docker it seems to of installed but is not displayed in my panels.
I also downloaded the zip file and dragged it over to my plugin folder.
It now appears in grafana but shows an error " Error loading: geeksrus-mqtt-panel "

Please is there a command line command that will install this into grafana for me using putty?

Thank you

**Comment by hildogjr** [comment]
You may have to add

```inf
[plugins]
allow_loading_unsigned_plugins = geeksrus-mqtt-panel
```

to the `grafana.ini` file to allow initialization of not assigned plugins, if you are using Grafana 8+.

**Comment by hildogjr** [comment]
After this I am experiencing some other issue (marking the author @geeks-r-us to give us some direction).

The plugin is loaded fine on Grafana 8.1 + docker  initialization, but I am getting the follow logging error in the screen when trying to add the `mqtt-panel` into my Grafana new panel (I had erased my server domain, in test):

```
An unexpected error happened
TypeError: this.events is undefined

tn@https://MY_DOMAIN.BR:3000/public/build/DashboardPage.d7cfb4e56c8be9229275.js:245:4464
E@https://MY_DOMAIN.BR:3000/public/build/vendors~app.d7cfb4e56c8be9229275.js:2:73696
div
div
div
t@https://MY_DOMAIN.BR:3000/public/build/vendors~app.d7cfb4e56c8be9229275.js:2:852952
h@https://MY_DOMAIN.BR:3000/public/build/app.d7cfb4e56c8be9229275.js:5740:36462
div
div
on@https://MY_DOMAIN.BR:3000/public/build/DashboardPage.d7cfb4e56c8be9229275.js:245:6715
div
div
wn@https://MY_DOMAIN.BR:3000/public/build/DashboardPage.d7cfb4e56c8be9229275.js:316:35
div
t@https://MY_DOMAIN.BR:3000/public/build/DashboardPage.d7cfb4e56c8be9229275.js:349:1556
div
t@https://MY_DOMAIN.BR:3000/public/build/DashboardPage.d7cfb4e56c8be9229275.js:349:3509
Jn@https://MY_DOMAIN.BR:3000/public/build/DashboardPage.d7cfb4e56c8be9229275.js:349:9139
div
div
vr@https://MY_DOMAIN.BR:3000/public/build/DashboardPage.d7cfb4e56c8be9229275.js:376:2172
E@https://MY_DOMAIN.BR:3000/public/build/vendors~app.d7cfb4e56c8be9229275.js:2:73696
div
E@https://MY_DOMAIN.BR:3000/public/build/DashboardPage.d7cfb4e56c8be9229275.js:426:994
DashboardPage
E@https://MY_DOMAIN.BR:3000/public/build/vendors~app.d7cfb4e56c8be9229275.js:2:73696
n@https://MY_DOMAIN.BR:3000/public/build/vendors~app.d7cfb4e56c8be9229275.js:2:545061
si@https://MY_DOMAIN.BR:3000/public/build/app.d7cfb4e56c8be9229275.js:5929:3214
t@https://MY_DOMAIN.BR:3000/public/build/vendors~app.d7cfb4e56c8be9229275.js:2:1380748
t@https://MY_DOMAIN.BR:3000/public/build/vendors~app.d7cfb4e56c8be9229275.js:2:1382793
main
t@https://MY_DOMAIN.BR:3000/public/build/vendors~app.d7cfb4e56c8be9229275.js:2:1377353
div
da@https://MY_DOMAIN.BR:3000/public/build/app.d7cfb4e56c8be9229275.js:3485:1227
t/ct/h<@https://MY_DOMAIN.BR:3000/public/build/app.d7cfb4e56c8be9229275.js:5738:20150
pl@https://MY_DOMAIN.BR:3000/public/build/app.d7cfb4e56c8be9229275.js:4162:682
hl@https://MY_DOMAIN.BR:3000/public/build/app.d7cfb4e56c8be9229275.js:4162:972
l@https://MY_DOMAIN.BR:3000/public/build/vendors~app.d7cfb4e56c8be9229275.js:2:71602
Ni@https://MY_DOMAIN.BR:3000/public/build/app.d7cfb4e56c8be9229275.js:5942:421
```



This error may also be the source of the comments in #26 (marking to close if the fix/solution attempt both). On Grafana versions < 8 this logging was not displayed in the page but the final behavior was the same. Possible the old Grafana version didn't have the capability of display the log.

**Comment by vindolin** [comment]
I have the same problem but only when I access my Grafana instance over HTTPS.
No problems over HTTP.

**Comment by hildogjr** [comment]
Me too, only under HTTPS, and only on first instantiation of the plugin. If I copy+paste a already configured dashboard, it works fine.

**Comment by duese456** [comment]
Looks like the same what hildogjr described above with Grafana v9.0.0: TypeError: this.events is undefined ... .
Any hint from somebody else?

**Comment by hildogjr** [comment]
@zoltan0907 proposed https://github.com/zoltan0907/mqtt-panel/commits?author=zoltan0907 for this issue rage l that we discussed in other thread.

**Comment by FlorianMESSINA** [comment]
@hildogjr the solution of @zoltan0907 works with grafana > 8 over https ?

**Comment by hildogjr** [comment]
I didn't test yet (I have not the prepared workspace to compile right now).

**Comment by tomy983** [comment]
Hi,
might be related. Running on Grafana 9.3.1 Message when adding the panel:

```
TypeError: Cannot read properties of undefined (reading 'emit')

    at bn (https://MYIPADDRESS/public/build/DashboardPage.8a1350f57b9b7c0796ec.js:102:1844)
    at g (https://MYIPADDRESS/public/build/2754.c9252327f51106ea3a6d.js:2:1042231)
    at div
    at div
    at div
    at t (https://MYIPADDRESS/public/build/2754.c9252327f51106ea3a6d.js:2:711588)
    at p (https://MYIPADDRESS/public/build/2352.d7c14cbd3dbda648a17f.js:424:3279)
    at div
    at div
    at Zn (https://MYIPADDRESS/public/build/DashboardPage.8a1350f57b9b7c0796ec.js:135:4496)
    at div
    at div
    at Ri (https://MYIPADDRESS/public/build/DashboardPage.8a1350f57b9b7c0796ec.js:258:27)
    at div
    at n (https://MYIPADDRESS/public/build/DashboardPage.8a1350f57b9b7c0796ec.js:37:6451)
    at div
    at n (https://MYIPADDRESS/public/build/DashboardPage.8a1350f57b9b7c0796ec.js:37:8400)
    at qt (https://MYIPADDRESS/public/build/DashboardPage.8a1350f57b9b7c0796ec.js:37:13987)
    at div
    at div
    at div
    at b (https://MYIPADDRESS/public/build/2352.d7c14cbd3dbda648a17f.js:5801:1143)
    at Ma (https://MYIPADDRESS/public/build/DashboardPage.8a1350f57b9b7c0796ec.js:381:1519)
    at g (https://MYIPADDRESS/public/build/2754.c9252327f51106ea3a6d.js:2:1042231)
    at WithTheme(Connect(Ma))
    at Dr (https://MYIPADDRESS/public/build/DashboardPage.8a1350f57b9b7c0796ec.js:504:7204)
    at DashboardPage
    at g (https://MYIPADDRESS/public/build/2754.c9252327f51106ea3a6d.js:2:1042231)
    at Suspense
    at c (https://MYIPADDRESS/public/build/2352.d7c14cbd3dbda648a17f.js:1207:301)
    at _c (https://MYIPADDRESS/public/build/2352.d7c14cbd3dbda648a17f.js:8832:350)
    at t (https://MYIPADDRESS/public/build/2754.c9252327f51106ea3a6d.js:2:1060624)
    at t (https://MYIPADDRESS/public/build/2754.c9252327f51106ea3a6d.js:2:1062645)
    at main
    at Cd (https://MYIPADDRESS/public/build/2352.d7c14cbd3dbda648a17f.js:8793:6820)
    at t (https://MYIPADDRESS/public/build/2754.c9252327f51106ea3a6d.js:2:1057242)
    at div
    at o (https://MYIPADDRESS/public/build/2352.d7c14cbd3dbda648a17f.js:1996:4308)
    at t.KBarProvider (https://MYIPADDRESS/public/build/2754.c9252327f51106ea3a6d.js:2:271053)
    at l (https://MYIPADDRESS/public/build/2352.d7c14cbd3dbda648a17f.js:6145:19538)
    at c (https://MYIPADDRESS/public/build/2352.d7c14cbd3dbda648a17f.js:1207:301)
    at u (https://MYIPADDRESS/public/build/2352.d7c14cbd3dbda648a17f.js:1207:855)
    at l (https://MYIPADDRESS/public/build/2754.c9252327f51106ea3a6d.js:2:1040276)
    at bu (https://MYIPADDRESS/public/build/2352.d7c14cbd3dbda648a17f.js:8845:115)
```
